#ifndef TILE_EDITOR_CONFIG_H
#define TILE_EDITOR_CONFIG_H

#define TILE_EDITOR
#define TILE_EDITOR_DEBUG

#define TILE_EDITOR_TITLE "Tile-Editor"
#define TILE_EDITOR_SCREEN_WIDTH 800
#define TILE_EDITOR_SCREEN_HEIGHT 600

#endif // TILE_EDITOR_CONFIG_H
